---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: lighthouse-audit-job
spec:
  schedule: "*/30 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: lighthouse-audit-job
              image: ellerbrock/alpine-bash-curl-ssl
              command: ["bash", "-c"]
              args: [
                'set -x;
                 for i in "${URLS[@]}";
                  do curl ${LIGHTHOUSE_URL}?url=${i}&mobile=${MOBILE}&userAgent=${USER_AGENT}&report=true&saveInDB=true;
                 done;
                ',
              ]
              env:
              - name: URLS
                value: (https://www.saksfifthavenue.com https://www.thebay.com https://www.lordandtaylor.com)
              - name: MOBILE
                value: "true"
              - name: USER_AGENT
                value: "Mozilla/5.0 (iPhone; CPU iPhone OS 11_0_3 like Mac OS X, ) AppleWebKit/604.1.38 (KHTML, like Gecko, HBC-Akamai-BOT) Mobile/15A432"
              - name: LIGHTHOUSE_URL
                value: http://inspector-lighthouse.observe.tools.common.awshbc.io/collect-one
          restartPolicy: Never
