apiVersion: apps/v1
kind: Deployment
metadata:
  name: inspector-lighthouse
  labels:
    app: inspector-lighthouse
spec:
  selector:
    matchLabels:
      app: inspector-lighthouse
  template:
    metadata:
      labels:
        app: inspector-lighthouse
    spec:
      containers:
        - name: inspector-lighthouse
          image: felicegeracitano/webperf-dashboard-lighthouse:2.0
          ports:
            - containerPort: 3000
          resources:
          env:
            - name: HOST
              value: influxdb

