apiVersion: v1
kind: Service
metadata:
  name: inspector-wpt
  annotations:
    {{ toYaml .Values.service.annotations | indent 4 }}
spec:
  ports:
  - name: inspector-wpt
    port: 80
    targetPort: 3000
  selector:
    app: inspector-wpt
  type: LoadBalancer
