apiVersion: v1
kind: Service
metadata:
  namespace: webperf
  name: wpt-server
spec:
  ports:
    - port: 30005
      targetPort: 80
      nodePort: 30005
  selector:
    app: wpt-server
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: webperf
  name: wpt-server
  labels:
    app: wpt-server
spec:
  selector:
    matchLabels:
      app: wpt-server
  template:
    metadata:
      labels:
        app: wpt-server
    spec:
      containers:
        - name: wpt-server
          image: felicegeracitano/local-wptagent
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          resources: