apiVersion: v1
kind: Service
metadata:
  namespace: webperf
  name: wpt-agent
spec:
  ports:
    - port: 30004
      targetPort: 80
      nodePort: 30004
  selector:
    app: wpt-agent
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: webperf
  name: wpt-agent
  labels:
    app: wpt-agent
spec:
  selector:
    matchLabels:
      app: "wpt-agent"
  template:
    metadata:
      labels:
        app: wpt-agent
    spec:
      containers:
        - name: wpt-agent
          image: local-wptagent
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          resources:
          env:
            - name: LOCATION
              value: Test
            - name: SERVER_URL
              value: http://wpt-server:30005/work/
